version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_vector_db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
